import { useRouter } from 'next/router';
//import { GTMnoscript } from '../components/GTM';

import Head from 'next/head';
import style from '../styles/Layout.module.css';
import Header from './Header';
import Menu from './Menu';
import styleAnimation from '../styles/StarsAnimation.module.css';

export default function Layout({ children }) {
  const router = useRouter();
  const name = router.query.name_project;
  return (
    <div>
      <Head>
        <title>Portafolio {name ? `| ${name}` : ''}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/*<GTMnoscript />*/}
      </Head>
      <Header />
      <Menu />
      <div className={style.container}>{children}</div>

      <div className={styleAnimation.starsAnimation}>
        <div className={styleAnimation.stars1}></div>
        <div className={styleAnimation.stars2}></div>
        <div className={styleAnimation.stars3}></div>
        <div className={styleAnimation.stars4}></div>
      </div>
    </div>
  );
}
